name: Docker Image CI

on: [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: checkout
        uses: actions/checkout@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: niroth36
          password: ${{ secrets.DOCKERTOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        
        with:
          context: .
          push: true
          tags: vetapp:latest
